CREATE TABLE APPLICATIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME VARCHAR(32) NOT NULL,
    LAST_NAME VARCHAR(32) NOT NULL,
    EMAIL VARCHAR (32) NOT NULL,
    PHONE VARCHAR(32) NOT NULL,
    NATIONALITY VARCHAR(32) NOT NULL,
    PASSPORT VARCHAR(32) NOT NULL,
    OCCUPATION VARCHAR(32) NOT NULL,


);